version: '3'

services:
  aline-capocci-database: 
    image: postgres:latest 
    container_name: aline-capocci-database 
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - aline-capocci-network

  web-project:
    hostname: "${HOSTNAME}"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/blog
    command: >
      bash -c "
        python manage.py runserver ${HOSTNAME}:${PORT}
      "
    volumes:
      - ./blog/:/usr/src/blog
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PYTHONUNBUFFERED=True
      - OAUTHLIB_INSECURE_TRANSPORT=False
    env_file:
      .env
    depends_on:
      - aline-capocci-database
    networks:
      - aline-capocci-network

networks:
  aline-capocci-network:
    external: true
