# Generated by Django 4.2.16 on 2025-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.AddField(
            model_name='article',
            name='is_news',
            field=models.BooleanField(default=False, verbose_name='is_news'),
        ),
    ]
